- hosts: all
  tasks:
    - name: get all addresses
      shell: ip -br addr | grep eth | grep -v eth0 | cut -d ' ' -f 1
      register: num_eths
      when: inventory_hostname in vars['config']

    - debug: var=num_eths

    - set_fact:
        ifaces: "{{ num_eths.stdout_lines }}"

    - name: flush interface
      command: ip addr flush {{ config[inventory_hostname].interface.name }}
      become: yes
      when: inventory_hostname in vars['config']

    - name: set addr interface
      command: ip addr add {{ config[inventory_hostname].interface.address }}/24 dev {{ config[inventory_hostname].interface.name }}
      become: yes
      when: inventory_hostname in vars['config']

    - name: set link up
      command: ip link set up {{ config[inventory_hostname].interface.name }}
      become: yes
      when: inventory_hostname in vars['config']
