- hosts: [isps, gateways]
  tasks:
    - name: copy over sys config file for forwarding from frr
      copy:
        src: ../files/sysctl.conf
        dest: /etc/sysctl.d/99frr_defaults.conf
      become: yes

    - name: set all sysctl values
      command: sysctl -p /etc/sysctl.d/99frr_defaults.conf
      become: yes

- hosts: all
  tasks:
    - name: get all addresses
      shell: ip -br addr | grep eth | grep -v eth0 | cut -d ' ' -f 1
      register: num_eths
      when: inventory_hostname in vars['config']

    - debug: var=num_eths

    - set_fact:
        ifaces: "{{ num_eths.stdout_lines }}"

    - name: flush interface before adding static routes
      command: ip addr flush {{ item }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      ignore_errors: yes
      become: yes
      when: inventory_hostname in vars['config']

    - name: addr interface
      command: ip addr add {{ vars['config'][inventory_hostname].interfaces[item]["address"] }}/{{ vars['config'][inventory_hostname].interfaces[item]["netmask"] }} dev {{ item }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      become: yes
      when: inventory_hostname in vars['config']

    - name: up interface
      command: ip link set dev {{ item }} up
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      become: yes
      when: inventory_hostname in vars['config']

    - name: add routes
      command: ip route add {{ vars['config'][inventory_hostname].routes[item][0] }} dev {{ item }}
      with_items:
        - "{{ vars['config'][inventory_hostname].routes | list }}"
      become: yes
      when: inventory_hostname in vars['config'] and "routes" in vars['config'][inventory_hostname]
