- hosts: [isps, gateways, apps, dnss, lighthouses]
  tasks:
    - name: get all addresses
      shell: ip -br addr | grep eth | grep -v eth0 | cut -d ' ' -f 1
      register: num_eths
      when: inventory_hostname in vars['config']

    #- debug: var=num_eths

    - set_fact:
        ifaces: "{{ num_eths.stdout_lines }}"

    - name: flush interface before adding static routes
      command: ip addr flush {{ item }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      ignore_errors: yes
      become: yes
      when: inventory_hostname in vars['config']

    - name: addr interface
      command: ip addr add {{ config[inventory_hostname].interfaces[item]["address"] }}/{{ config[inventory_hostname].interfaces[item]["netmask"] }} dev {{ item }}
      with_items:
        - "{{ config[inventory_hostname].interfaces | list }}"
      become: yes
      when: inventory_hostname in config and "address" in config[inventory_hostname].interfaces[item]

    - name: up interface
      command: ip link set dev {{ item }} up
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      become: yes
      when: inventory_hostname in vars['config']

- hosts: [isps]
  become: yes
  tasks:
    - name: Recursively remove directory
      file:
        path: /etc/apt/sources.list.d/frr.list
        state: absent

    - name: install lsb-release for frr script
      shell: apt-get --allow-releaseinfo-change update

    - name: install lsb-release for frr script
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - lsb-release
        - gnupg2

    - name: copy frr deb script
      copy:
        src: ../files/add-frr.sh
        dest: /etc/apt/add-frr.sh
        owner: root
        group: root
        mode: 0755
 
    # bug in current frr 7.5.1 with ospfv6, missing conf t, int eth1, ipv6 ospf6 area option (which enables ospf on the interface- big oops)   
    - name: install frr from deb
      command: /etc/apt/add-frr.sh

    - name: install networking packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - ntp
        - ethtool
        - frr
        - tcpdump
        - lldpd

    - name: stop frr
      systemd:
        name: frr
        state: stopped

    - name: copy over sys config file for forwarding from frr
      copy:
        src: ../files/sysctl.conf
        dest: /etc/sysctl.d/99frr_defaults.conf

    - name: set all sysctl values
      command: sysctl -p /etc/sysctl.d/99frr_defaults.conf

    - name: copy over daemons file
      copy:
        src: ../files/daemons
        dest: /etc/frr/daemons

    - name: copy over frr template
      template:
        src: ../templates/frr.conf
        dest: /etc/frr/frr.conf

    - name: reload frr
      systemd:
        name: frr
        daemon_reload: yes
        state: reloaded

    - name: restart frr
      systemd:
        name: frr
        state: restarted

- hosts: [isps]
  become: yes
  tasks:
    - name: install dnsmasq for dhcp servers
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - dnsmasq

    - name: ensure dnsmasq is not running
      command: killall dnsmasq
      ignore_errors: yes

    # TODO: check if 
    - name: begin running dnsmasq
      command: dnsmasq --interface={{ item }} --except-interface=lo --bind-interfaces --dhcp-range={{ config[inventory_hostname].interfaces[item].dhcp.range.start }},{{ config[inventory_hostname].interfaces[item].dhcp.range.end }},1h --dhcp-option=121,10.0.0.0/8,{{ config[inventory_hostname].interfaces[item].address }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      when: inventory_hostname in vars['config'] and "dhcp" in config[inventory_hostname].interfaces[item]


- hosts: all
  tasks:
    - name: dhcp interface
      command: dhclient -v -4 {{ item }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces | list }}"
      become: yes
      when: inventory_hostname in vars['config'] and "address" not in config[inventory_hostname].interfaces[item]
