---
# install and configure etcd
- hosts: [apps]
  become: true
  tasks:
    - import_role:
        name: etcd
      vars:
        server: yes
        alias: "{{ vars[inventory_hostname_short].alias }}"
        address: "{{ inventory_hostname }}.{{ nebula_network_fqdn }}"
        ip: "{{ overlay[inventory_hostname].ip }}"
