---
# generate keys
#- hosts: localhost
#  tasks:
#    - import_role:
#        name: etcd
#      vars:
#        keygen: yes
#        local: yes
#        auth_hosts:
#          - db0,app0,{{ config["app0"]["wireguard"]["address"] }}
#          - db1,app1,{{ config["app1"]["wireguard"]["address"] }}
#          - db2,app2,{{ config["app2"]["wireguard"]["address"] }}

# install and configure etcd
- hosts: [apps]
  become: true
  vars:
    app1:
      alias: db1
    app2:
      alias: db2
    app3:
      alias: db3
  tasks:
    - import_role:
        name: etcd
      vars:
        server: yes
        alias: "{{ vars[inventory_hostname_short].alias }}"
        address: "{{ inventory_hostname_short }}"
        ip: "{{ overlay[inventory_hostname].ip }}"
        hosts:
          - alias: db1
            endpoint: db1=https://app1:2380
          - alias: db2
            endpoint: db2=https://app2:2380
          - alias: db3
            endpoint: db0=https://app3:2380

# create a proxy on the gateways
#- hosts: [gateways]
#  become: true
#  tasks:
#    - file:
#        path: /etc/etcd
#        state: directory
#
#    - copy:
#        src: "{{item}}"
#        dest: /etc/etcd/{{item}}
#      loop: [ca.pem, db.pem, db-key.pem]
#
#    - import_role:
#        name: etcd
#      vars:
#        proxy: yes
#        proxy_name: avoid-dns
#        proxy_address: 127.0.0.1
#        proxy_port: 2399
#        proxy_endpoints: https://app0:2379,https://app1:2379,https://app2:2379
#        ca_pem: ./ca.pem
#        db_pem: ./db.pem
#        db_key: ./db-key.pem
