- hosts: [gateways, apps]
  tasks:
    - name: update cache
      apt:
        update_cache: yes
      become: yes

    # https://github.com/githubixx/ansible-role-wireguard/blob/master/tasks/setup-ubuntu.yml#L23C1-L27C18
    - name: Ensure WireGuard DKMS package is removed
      ansible.builtin.apt:
        name:
          - "wireguard-dkms"
        state: absent

    - name: install wireguard, QR encoder, wget, curl, tcpdump
      apt:
        update_cache: yes
        pkg:
         - wireguard
         - qrencode
         - wget
         - curl
         - tcpdump
      become: yes

    - name: stop wireguard
      shell: wg-quick down {{ iface_name }}.conf
      args:
        chdir: /home/rvn
      ignore_errors: yes
      become: yes

    - name: flush wg interface
      shell: ip addr flush {{ iface_name }}
      ignore_errors: yes
      become: yes

    - name: delete wg interface
      shell: ip link del {{ iface_name }}
      ignore_errors: yes
      become: yes

    - name: flush ip table rules
      shell: iptables -F
      ignore_errors: yes
      become: yes

    - name: flush ip table rules for nat
      shell: iptables -t nat -F
      ignore_errors: yes
      become: yes

    # https://www.wireguard.com/quickstart/
    - name: create a wireguard pub, private key
      shell: wg genkey | tee privatekey | wg pubkey > publickey
      args:
        chdir: /home/rvn

    - name: get wg private key
      shell: cat privatekey
      args:
        chdir: /home/rvn
      register: wgpriv

    - name: set wg private key variable
      set_fact:
        private_key: "{{ wgpriv.stdout }}"

        #config: "{{ config|combine({inventory_hostname: {'wireguard': {'private_key': wgpriv.stdout}}}, recursive=True) }}"

    - name: get wg public key
      shell: cat publickey
      args:
        chdir: /home/rvn
      register: wgpub

    - name: set wg public key variable
      set_fact:
        public_key: "{{ wgpub.stdout }}"

    # TODO: there will be issues if new lease given with different ip
    - name: get our wireguard address that has been dhcp'd
      shell: ip -br addr | grep eth1 | sed 's/ \+/ /g' | cut -d ' ' -f 3 | cut -d '/' -f 1
      register: eths
      when: inventory_hostname in vars['config']

    - set_fact:
        wireguard_address: "{{ item }}"
      with_items:
        - "{{ eths.stdout_lines }}"

- hosts: [gateways, apps]
  tasks:
    # the name of the file dictates the interface name
    # https://github.com/pirate/wireguard-docs?tab=readme-ov-file#overview
    - name: copy over our template files
      template: 
        src: ../templates/wireguard-server.conf
        dest: /etc/wireguard/{{ iface_name }}.conf
      become: yes
      when: '"gw" in inventory_hostname'

    - name: copy over our template files
      template:
        src: ../templates/wireguard-client.conf
        dest: /etc/wireguard/{{ iface_name }}.conf
      become: yes
      when: '"gw" not in inventory_hostname'

    - name: start wireguard (emphemeral)
      shell: wg-quick up {{ iface_name }}
      args:
        chdir: /home/rvn
      become: yes
