- hosts: [nebula, lighthouses]
  tasks:
    - name: install jq
      apt:
        pkg: jq
        state: latest
      become: yes

    - name: get all ip addresses for interfaces
      shell: ip -json -br addr | jq '.[] | select(.ifname == "neb1").addr_info[] | select(.local|startswith("192")).local' | sed 's/"//g'
      register: eths
      when: inventory_hostname in overlay

    - set_fact:
        ifaces: "{{ ifaces | default([]) + [item] }}"
      with_items:
        - "{{ eths.stdout_lines }}"

    - debug: var=ifaces

    # everything except gw0 which isnt in the overlay
    - name: set hostnames
      set_fact:
        hostnames: "{{ overlay | list | difference(['avoid-gw0']) }}"

    - debug: var=hostnames

    - name: set dicts
      set_fact:
        #all_ips: "{{ all_ips|default({})|combine({item: hostvars[item]['ifaces'] }) }}"
        all_ips: "{{ all_ips|default([]) + hostvars[item]['ifaces'] }}"
      with_items:
        - "{{ hostnames }}"
      when: '"ue" not in item'

#    - debug: var=all_ips

#    - name: set flat
#      set_fact:
#        all_flat: "{{ all_ips|flatten }}"
#
#    - debug: var=all_flat

    - name: ping all other interfaces for reachability
      shell: ping -c 5 {{ item }}
      with_items:
        - "{{ all_ips }}"
