# configure our cumulus linux host as a switch
---

- hosts: sws
  become: yes
  tasks:
    - name: count the swps
      shell: ip -br link | grep swp | cut -d ' ' -f 1
      register: ports

    - name: set swps variable
      set_fact:
        swps: "{{ ports.stdout_lines }}"

    - name: print fact
      debug: var=swps

    - name: configure interfaces
      template:
        src: ../templates/switch_interfaces.conf
        dest: /etc/network/interfaces

    - name: reload interfaces
      shell: ifreload -a
      ignore_errors: yes
