nebula_iface_name: neb1
nebula_network_domain: avoid-nebula
nebula_network_fqdn: avoid-nebula.org
overlay:
  'lh0':
     ip: 192.168.0.1
     netmask: 24
     network: nebula
  'avoid-gw0':
     ip: 192.168.0.10
     netmask: 24
     network: nebula
  'avoid-gw1':
     ip: 192.168.0.11
     netmask: 24
     network: nebula
  'avoid-gw2':
     ip: 192.168.0.12
     netmask: 24
     network: nebula
  'avoid-gw3':
     ip: 192.168.0.13
     netmask: 24
     network: nebula
  'ue':
     ip: 192.168.0.100
     netmask: 24
     network: nebula
  'app1':
     ip: 192.168.0.21
     netmask: 24
     network: nebula
  'app2':
     ip: 192.168.0.22
     netmask: 24
     network: nebula
  'app3':
     ip: 192.168.0.23
     netmask: 24
     network: nebula

config:
  'ue':
    interfaces:
      eth1:
        dhcp: yes
        network: isp0
      eth2:
        dhcp: no
        network: isp1
      eth3:
        dhcp: no
        network: isp2

  'isp0':
    interfaces:
      eth1:
        address: 10.0.0.1
        network: ue
        netmask: 24
        dhcp:
          range:
            start: 10.0.0.10
            end:   10.0.0.20
      eth2:
        address: 10.0.10.10
        network: isp1
        netmask: 24
      eth3:
        address: 10.10.10.1
        network: sw0
        netmask: 24
        dhcp:
          range:
            start: 10.10.10.10
            end:   10.10.10.20
      eth4:
        address: 10.10.0.100
        network: sw3
        netmask: 24
    ospf:
      eth2:
        area: 10
        
  'isp1':
    interfaces:
      eth1:
        address: 10.0.1.1
        network: ue
        netmask: 24
        dhcp:
          range:
            start: 10.0.1.10
            end:   10.0.1.20
      eth2:
        address: 10.0.10.11
        network: isp0
        netmask: 24
      eth3:
        address: 10.0.11.10
        network: isp2
        netmask: 24
      eth4:
        address: 10.10.11.1
        network: sw1
        netmask: 24
        dhcp:
          range:
            start: 10.10.11.10
            end:   10.10.11.20
      eth5:
        address: 10.10.0.101
        network: sw3
        netmask: 24
    ospf:
      eth2:
        area: 0
      eth3:
        area: 0
      eth4:
        area: 0

  'isp2':
    interfaces:
      eth1:
        address: 10.0.2.1
        network: ue
        netmask: 24
        dhcp:
          range:
            start: 10.0.2.10
            end: 10.0.2.20
      eth2:
        address: 10.0.11.12
        network: isp1
        netmask: 24
      eth3:
        address: 10.10.12.1
        network: sw2
        netmask: 24
        dhcp:
          range:
            start: 10.10.12.10
            end:   10.10.12.20
      eth4:
        address: 10.3.0.1
        network: sw3
        netmask: 24
    ospf:
      eth2:
        area: 12

  'isp3':
    interfaces:
      eth1:
        address: 10.10.11.2
        network: isp1
        netmask: 8
      eth2:
        address: 10.10.13.1
        network: avoid-gw3
        netmask: 24
        dhcp:
          range:
            start: 10.10.13.10
            end:   10.10.13.20
      eth3:
        address: 10.10.14.1
        network: app3
        netmask: 24
        dhcp:
          range:
            start: 10.10.14.10
            end:   10.10.14.20
    ospf:
      eth1:
        area: 13

  'avoid-gw0':
    interfaces:
      eth1:
        network: isp0
        dhcp: yes

  'avoid-gw1':
    interfaces:
      eth1:
        network: isp1
        dhcp: yes

  'avoid-gw2':
    interfaces:
      eth1:
        network: isp2
        dhcp: yes

  'avoid-gw3':
    interfaces:
      eth1:
        network: isp3
        dhcp: yes

  'app1':
    interfaces:
      eth1:
        network: avoid-gw1
        dhcp: yes

  'app2':
    interfaces:
      eth1:
        network: avoid-gw2
        dhcp: yes

  'app3':
    interfaces:
      eth1:
        network: isp3
        dhcp: yes

  'dns':
    interfaces:
      eth1:
        address: 10.10.0.11
        network: isps
        netmask: 8

  'authority':
    interfaces:
      eth1:
        address: 10.10.0.10
        network: isps
        netmask: 8

  'lh0':
    interfaces:
      eth1:
        address: 10.10.10.2
        network: isp0
        netmask: 8
